### ISSUE TITLE
3D model

### ISSUE THREAD

**Issue by Woongbin06** [BSSM-Google-hackathon/My-Eco-City-Frontend#5]
나무 : https://sketchfab.com/3d-models/tree-lp-c76ca4c065824faca1006b07252b1c17
드론 : https://sketchfab.com/3d-models/s9-mini-drone-cf3ed83c1b87486d90435f54c074e16e

**Comment by Woongbin06** [comment]
https://sketchfab.com/3d-models/solar-panel-ff765abe2d324c91899541b43cc40c72

**Comment by Woongbin06** [comment]
https://sketchfab.com/3d-models/cctv-camera-minimal-553ace160b8c4eb2a62b755ffdb7b6eb

**Comment by Woongbin06** [comment]
나무 : ![image](https://user-images.githubusercontent.com/95995962/178962520-65ba6b62-4b83-4b29-b1df-217c04fbccef.png)
드론 : ![image](https://user-images.githubusercontent.com/95995962/178962684-bfad6e39-b144-4432-9199-9538937f0e3d.png)
태양광 : ![image](https://user-images.githubusercontent.com/95995962/178962822-d313d4b3-1d64-4761-b29e-264806b7e837.png)

**Comment by min050410** [comment]
감사합니다
