### ISSUE TITLE
3D model

### ISSUE THREAD

**Issue by Yujeong12** [BSSM-Google-hackathon/My-Eco-City-Frontend#6]
https://sketchfab.com/3d-models/modern-bench-1-caa4515e36444e4c8c100296463e83c1
https://sketchfab.com/3d-models/57484-photovoltaic-panel-cycles-1b0086380b6a401489d76ac5a1b8429b
https://sketchfab.com/3d-models/bicycle-197dd882a69846e0825e80566996cbba
https://sketchfab.com/3d-models/chargepoint-express-250-transparent-house-demo-9b6eed32d79f4ad4918a07048f7317fc
https://sketchfab.com/3d-models/wind-turbine-285032402a8543ae8bf3e3c4d8c9f98a
https://sketchfab.com/3d-models/free-honda-e-detailed-interior-2021-814cf3f8cfd64594b1c4f96e873c3cef

**Comment by Yujeong12** [comment]
![image](https://user-images.githubusercontent.com/102145368/178963019-5e431dc9-d0e6-4d58-90b1-dbcbd5c3f6be.png)
벤치

**Comment by Yujeong12** [comment]
![image](https://user-images.githubusercontent.com/102145368/178963164-f4ef0420-c172-4a16-b39c-1a02477a5c8c.png)
자전거

**Comment by Woongbin06** [comment]
자동차 : ![image](https://user-images.githubusercontent.com/95995962/178963068-ecccf6bf-2e2f-4b35-ba71-6b0a3522f869.png)
풍력 : ![image](https://user-images.githubusercontent.com/95995962/178963252-1d1c310a-3b0b-4881-914e-eec204f06d56.png)

**Comment by min050410** [comment]
감사합니다
